// Alertas verificadas de Santa Cruz — mayo 2026
// Fuentes: Infobae, El Socavón, OPI SC, Noticias Santa Cruz,
//          ZN Noticias, ATE Argentina, La Prensa de Santa Cruz
// Se usan como fallback cuando la tabla problematicas_sc está vacía

export interface AlertaSeed {
  id: number
  localidadSlug: string
  localidadNombre: string
  categoria: string
  titulo: string
  fuenteNombre: string
  url: string | null
  severidad: 1 | 2 | 3
  publicadoAt: string
}

export const ALERTAS_SC_SEED: AlertaSeed[] = [
  // ===== SEVERIDAD 3 — CRISIS =====

  {
    id: 9001,
    localidadSlug: 'perito-moreno-sc',
    localidadNombre: 'Perito Moreno',
    categoria: 'salud',
    titulo: 'TRAGEDIA: Explosión de garrafa deja 3 muertos — bebé de 2 meses, Franco Gómez (26) y Jorge Valconte (30). Cuatro menores y una mujer en estado crítico. Dos niños trasladados a Buenos Aires por quemaduras graves',
    fuenteNombre: 'Infobae / Noticias Santa Cruz',
    url: 'https://noticias.santacruz.gob.ar/gestion/gobierno/item/38223-tragedia-en-perito-moreno-explosion',
    severidad: 3,
    publicadoAt: '2026-05-11T00:00:00Z',
  },
  {
    id: 9002,
    localidadSlug: 'perito-moreno-sc',
    localidadNombre: 'Perito Moreno',
    categoria: 'politica',
    titulo: 'Gobierno decretó 3 días de duelo provincial. Peritos confirman garrafa como causa. Edificio demolido. Dispositivo especial de asistencia a familias activado',
    fuenteNombre: 'Noticias Santa Cruz',
    url: 'https://noticias.santacruz.gob.ar/gestion/gobierno/item/38224-duelo-perito-moreno',
    severidad: 3,
    publicadoAt: '2026-05-11T08:00:00Z',
  },
  {
    id: 9003,
    localidadSlug: 'rio-gallegos',
    localidadNombre: 'Río Gallegos',
    categoria: 'protesta',
    titulo: 'ADOSAC y AMET anuncian paro docente de 96 horas (12-15 mayo): salarios congelados desde enero, sin paritarias, descuentos ilegales por huelgas previas. Santa Cruz al borde de crisis salarial docente',
    fuenteNombre: 'El Socavón / OPI Santa Cruz',
    url: 'https://www.multimedioelsocavon.com.ar/2026/05/12/amet-y-adosac-anunciaron-paro-96-horas',
    severidad: 3,
    publicadoAt: '2026-05-12T00:00:00Z',
  },
  {
    id: 9004,
    localidadSlug: 'rio-turbio',
    localidadNombre: 'Río Turbio',
    categoria: 'protesta',
    titulo: 'SOEM en paro indefinido: municipales exigen 47% de aumento, municipio ofreció 13%. Acatamiento 90%+. Cortes de ruta intermitentes. Demanda judicial contra intendente Menna por retención de aportes ($120M+)',
    fuenteNombre: 'El Socavón',
    url: 'https://www.multimedioelsocavon.com.ar/2026/05/07/conflicto-salarial-rio-turbio-soem-paro',
    severidad: 3,
    publicadoAt: '2026-05-07T00:00:00Z',
  },

  // ===== SEVERIDAD 2 — PROBLEMA SERIO =====

  {
    id: 9005,
    localidadSlug: 'rio-gallegos',
    localidadNombre: 'Río Gallegos',
    categoria: 'protesta',
    titulo: '"Ruidazo" en Av. Kirchner y San Martín: gremios exigen paritarias y rechazan descuentos salariales aplicados ilegalmente por el gobierno provincial (7 mayo)',
    fuenteNombre: 'El Socavón',
    url: 'https://www.multimedioelsocavon.com.ar/2026/05/08/ruidazo-rio-gallegos-paritarias',
    severidad: 2,
    publicadoAt: '2026-05-07T00:00:00Z',
  },
  {
    id: 9006,
    localidadSlug: 'rio-gallegos',
    localidadNombre: 'Río Gallegos',
    categoria: 'infraestructura',
    titulo: 'Desborde cloacal por lluvia: SPSE denuncia que el Municipio descarga pluviales en la red cloacal provincial, generando emergencias sanitarias reiteradas en la capital',
    fuenteNombre: 'OPI Santa Cruz',
    url: 'https://opisantacruz.com.ar/2026/05/colapso-cloacal-rio-gallegos-lluvias',
    severidad: 2,
    publicadoAt: '2026-05-09T00:00:00Z',
  },
  {
    id: 9007,
    localidadSlug: 'rio-turbio',
    localidadNombre: 'Río Turbio',
    categoria: 'protesta',
    titulo: 'UOCRA protesta frente a oficina del CPE por falta de trabajo y promesas incumplidas al sector de la construcción (14 mayo 2026)',
    fuenteNombre: 'El Socavón',
    url: 'https://www.multimedioelsocavon.com.ar/2026/05/14/uocra-rio-turbio-falta-trabajo',
    severidad: 2,
    publicadoAt: '2026-05-14T00:00:00Z',
  },
  {
    id: 9008,
    localidadSlug: 'rio-turbio',
    localidadNombre: 'Río Turbio',
    categoria: 'economia',
    titulo: 'YCRT: interventor cuestionado judicialmente. La empresa carbonífera recibió ofertas de privatización parcial por USD 20-25 millones. Incertidumbre laboral para mineros del carbón',
    fuenteNombre: 'OPI Santa Cruz',
    url: 'https://opisantacruz.com.ar/2026/05/ycrt-privatizacion-ofertas-millones',
    severidad: 2,
    publicadoAt: '2026-05-10T00:00:00Z',
  },
  {
    id: 9009,
    localidadSlug: 'pico-truncado',
    localidadNombre: 'Pico Truncado',
    categoria: 'seguridad',
    titulo: 'Robo de automóvil con extorsión para recuperarlo. La víctima reveló que de 150 cámaras de seguridad instaladas en la ciudad, solo 50 funcionan activamente',
    fuenteNombre: 'El Diario Nuevo Día',
    url: 'https://www.eldiarionuevodia.com.ar/locales/pico-truncado-camaras-seguridad-robo-2026',
    severidad: 2,
    publicadoAt: '2026-05-08T00:00:00Z',
  },
  {
    id: 9010,
    localidadSlug: 'pico-truncado',
    localidadNombre: 'Pico Truncado',
    categoria: 'protesta',
    titulo: 'ATE Pico Truncado y Frente Sindical se reúnen con concejales para documento de apoyo a trabajadores durante el paro docente y estatal provincial (7 mayo)',
    fuenteNombre: 'ATE Argentina',
    url: 'https://ate.org.ar/260507-picotruncado-santacruz-paro',
    severidad: 2,
    publicadoAt: '2026-05-07T00:00:00Z',
  },
  {
    id: 9011,
    localidadSlug: 'caleta-olivia',
    localidadNombre: 'Caleta Olivia',
    categoria: 'politica',
    titulo: 'Elecciones internas del PJ impugnadas y suspendidas judicialmente en Caleta Olivia. Proceso cuestionado formalmente ante la justicia electoral provincial',
    fuenteNombre: 'ZN Noticias',
    url: 'https://znnoticias.com/2026/05/caleta-olivia-pj-elecciones-impugnadas',
    severidad: 2,
    publicadoAt: '2026-05-06T00:00:00Z',
  },
  {
    id: 9012,
    localidadSlug: 'las-heras-sc',
    localidadNombre: 'Las Heras',
    categoria: 'protesta',
    titulo: 'Paro docente ADOSAC 96 horas (12-15 mayo) afecta todas las escuelas de Las Heras. Santa Cruz al borde de crisis salarial docente junto a Río Negro y Tierra del Fuego',
    fuenteNombre: 'Ámbito / OPI Santa Cruz',
    url: 'https://www.ambito.com/conflictos-docentes-santa-cruz-crisis-salarial-2026',
    severidad: 2,
    publicadoAt: '2026-05-12T00:00:00Z',
  },
  {
    id: 9013,
    localidadSlug: 'puerto-san-julian',
    localidadNombre: 'Puerto San Julián',
    categoria: 'protesta',
    titulo: 'Paro docente ADOSAC 96 horas afecta escuelas de Puerto San Julián. Sin acuerdo paritario desde enero. Docentes con salarios congelados y descuentos ilegales aplicados',
    fuenteNombre: 'OPI Santa Cruz',
    url: 'https://www.opisantacruz.com.ar/2026/05/05/adosac-paro-san-julian',
    severidad: 2,
    publicadoAt: '2026-05-12T01:00:00Z',
  },

  // ===== SEVERIDAD 1 — INFORMATIVO =====

  {
    id: 9014,
    localidadSlug: 'caleta-olivia',
    localidadNombre: 'Caleta Olivia',
    categoria: 'infraestructura',
    titulo: 'Gobierno provincial y municipio de Caleta Olivia avanzan en agenda conjunta de obras, financiamiento y desarrollo local',
    fuenteNombre: 'ZN Noticias',
    url: 'https://znnoticias.com/2026/05/05/gobierno-santa-cruz-caleta-olivia-agenda-conjunta',
    severidad: 1,
    publicadoAt: '2026-05-05T00:00:00Z',
  },
  {
    id: 9015,
    localidadSlug: 'el-calafate',
    localidadNombre: 'El Calafate',
    categoria: 'economia',
    titulo: 'Glaciar Perito Moreno bate récords de visitantes en temporada 2025-2026. El Calafate se consolida como capital patagónica del turismo con cifras históricas de ocupación hotelera',
    fuenteNombre: 'La Opinión Austral',
    url: 'https://laopinionaustral.com.ar/el-calafate/record-visitantes-glaciar-2026',
    severidad: 1,
    publicadoAt: '2026-05-03T00:00:00Z',
  },
  {
    id: 9016,
    localidadSlug: 'puerto-deseado',
    localidadNombre: 'Puerto Deseado',
    categoria: 'infraestructura',
    titulo: 'Inversión superior a $15.000 millones para fortalecimiento del puerto y obras en Ruta 281. Convenio para infraestructura de energía, agua potable y saneamiento en Puerto Deseado',
    fuenteNombre: 'Noticias Santa Cruz',
    url: 'https://noticias.santacruz.gob.ar/gestion/gobierno/item/38188-puerto-deseado-inversion',
    severidad: 1,
    publicadoAt: '2026-05-08T00:00:00Z',
  },
  {
    id: 9017,
    localidadSlug: 'puerto-deseado',
    localidadNombre: 'Puerto Deseado',
    categoria: 'salud',
    titulo: 'Inauguración de salas de kinesiología y oncología en el Hospital de Puerto Deseado. Evita traslados de 200-300 km para tratamientos oncológicos',
    fuenteNombre: 'Noticias Santa Cruz',
    url: 'https://noticias.santacruz.gob.ar/gestion/gobierno/item/38189-hospital-deseado-oncologia',
    severidad: 1,
    publicadoAt: '2026-05-06T00:00:00Z',
  },
  {
    id: 9018,
    localidadSlug: 'gobernador-gregores',
    localidadNombre: 'Gobernador Gregores',
    categoria: 'infraestructura',
    titulo: 'Vidal inaugura cancha de césped sintético en Gregores — quinta cancha entregada en la provincia. Nueva Planta Peletizadora para diversificación productiva y generación de empleo local',
    fuenteNombre: 'ZN Noticias',
    url: 'https://znnoticias.com/2026/05/05/planta-peletizadora-gobernador-gregores',
    severidad: 1,
    publicadoAt: '2026-05-05T00:00:00Z',
  },
  {
    id: 9019,
    localidadSlug: 'gobernador-gregores',
    localidadNombre: 'Gobernador Gregores',
    categoria: 'politica',
    titulo: 'Inauguración del jardín de infantes "La Casita Encantada": obra paralizada desde 2019, finalmente terminada tras 7 años de espera. Primer jardín nuevo en Gregores en más de una década',
    fuenteNombre: 'La Prensa de Santa Cruz',
    url: 'https://www.laprensadesantacruz.com/2026/05/09/casita-encantada-gregores',
    severidad: 1,
    publicadoAt: '2026-05-09T00:00:00Z',
  },
  {
    id: 9020,
    localidadSlug: 'el-chalten',
    localidadNombre: 'El Chaltén',
    categoria: 'economia',
    titulo: 'Fiesta Nacional del Trekking 2026 con alta ocupación hotelera. El Chaltén reafirma su posición como Capital Nacional del Trekking con actividades culturales y deportivas',
    fuenteNombre: 'Municipalidad El Chaltén',
    url: 'https://www.elchalten.gob.ar/fnt-2026',
    severidad: 1,
    publicadoAt: '2026-05-10T00:00:00Z',
  },
  {
    id: 9021,
    localidadSlug: 'el-chalten',
    localidadNombre: 'El Chaltén',
    categoria: 'salud',
    titulo: 'Operativo "La Salud va a la Escuela": 100 dosis de vacunas aplicadas en escuelas de El Chaltén. Primer retiro de reciclables del año y control de fauna urbana',
    fuenteNombre: 'Municipalidad El Chaltén',
    url: 'https://www.elchalten.gob.ar/salud-escuela-2026',
    severidad: 1,
    publicadoAt: '2026-05-14T00:00:00Z',
  },
  {
    id: 9022,
    localidadSlug: 'tres-lagos',
    localidadNombre: 'Tres Lagos',
    categoria: 'infraestructura',
    titulo: 'Inauguración del Gimnasio Comunal renovado de Tres Lagos. Ampliación red de agua potable beneficia 45 familias del sector norte. Apoyo del gobierno provincial',
    fuenteNombre: 'El Diario Nuevo Día',
    url: 'https://www.eldiarionuevodia.com.ar/locales/tres-lagos-gimnasio-agua-2026',
    severidad: 1,
    publicadoAt: '2026-05-01T00:00:00Z',
  },
  {
    id: 9023,
    localidadSlug: 'puerto-santa-cruz',
    localidadNombre: 'Puerto Santa Cruz',
    categoria: 'economia',
    titulo: 'Avanzan obras del Proyecto Avícola Integral en Puerto Santa Cruz: producción de pollos, alimento balanceado y piscicultura de robalo. Diversificación productiva en marcha',
    fuenteNombre: 'Tiempo Sur',
    url: 'https://www.tiemposur.com.ar/info-general/proyecto-avicola-puerto-santa-cruz-2026',
    severidad: 1,
    publicadoAt: '2026-05-04T00:00:00Z',
  },
  {
    id: 9024,
    localidadSlug: 'perito-moreno-sc',
    localidadNombre: 'Perito Moreno',
    categoria: 'infraestructura',
    titulo: 'Reactivación de línea eléctrica alta tensión El Pluma–Perito Moreno–Los Antiguos: USD 19.5 millones. Auditorio Edmundo Águila + obras por $4.600 millones anunciadas antes de la tragedia',
    fuenteNombre: 'Noticias Santa Cruz',
    url: 'https://noticias.santacruz.gob.ar/gestion/gobierno/item/38100-perito-moreno-linea-electrica',
    severidad: 1,
    publicadoAt: '2026-05-02T00:00:00Z',
  },
  {
    id: 9025,
    localidadSlug: 'los-antiguos',
    localidadNombre: 'Los Antiguos',
    categoria: 'protesta',
    titulo: 'Paro docente provincial ADOSAC-AMET afecta escuelas de Los Antiguos. Conflicto salarial sin resolución desde enero en toda la provincia',
    fuenteNombre: 'OPI Santa Cruz',
    url: 'https://www.opisantacruz.com.ar/2026/05/05/adosac-paro-los-antiguos',
    severidad: 1,
    publicadoAt: '2026-05-12T02:00:00Z',
  },
  {
    id: 9026,
    localidadSlug: 'piedra-buena',
    localidadNombre: 'Piedra Buena',
    categoria: 'protesta',
    titulo: 'Paro docente ADOSAC afecta Piedra Buena. Docentes exigen paritarias y rechazan descuentos por días de huelga aplicados ilegalmente',
    fuenteNombre: 'OPI Santa Cruz',
    url: 'https://www.opisantacruz.com.ar/2026/05/05/adosac-paro-piedra-buena',
    severidad: 1,
    publicadoAt: '2026-05-12T03:00:00Z',
  },
  {
    id: 9027,
    localidadSlug: '28-de-noviembre',
    localidadNombre: '28 de Noviembre',
    categoria: 'protesta',
    titulo: 'Paro docente ADOSAC-AMET afecta 28 de Noviembre. Ciudad minera también afectada por incertidumbre sobre el futuro de YCRT',
    fuenteNombre: 'OPI Santa Cruz',
    url: 'https://opisantacruz.com.ar/2026/05/adosac-paro-28-noviembre',
    severidad: 1,
    publicadoAt: '2026-05-12T04:00:00Z',
  },
]
